# Generated by Django 5.1.6 on 2025-02-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_trip_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date']},
        ),
    ]
