# Generated by Django 5.1.3 on 2024-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
