# Generated by Django 5.1.6 on 2025-02-28 06:35

import django.core.validators
import fruitipediaApp.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long.'), fruitipediaApp.accounts.validators.validate_first_letter])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1, message='Last name must be at least 1 characters long.'), fruitipediaApp.accounts.validators.validate_first_letter])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(help_text='*Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.')])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
